spring.datasource.url=jdbc:postgresql://localhost:5432/extreme_db
spring.datasource.username=extreme_user
spring.datasource.password=extreme_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
